import { ArtFeedback } from './art-feedback';
import { Artist } from './artist';
import { Category } from './category';
import { Collection } from './collection';
import { UploadFile } from './file';
import { Tag } from './tag';
import { User } from './user';
import { StrapiCollection, StrapiEntity } from './strapi';
import { Comment } from './comment';

export type Art = {
  id: number;
  title: string;
  slug: string;
  description: string;
  content: string;
  images: StrapiCollection<UploadFile>;
  status: 'pending' | 'rejected' | 'approved';
  previousStatus: 'pending' | 'rejected' | 'approved';
  likes: number;
  views: number;
  locale: string;
  artist: StrapiEntity<Artist>;
  categories: StrapiCollection<Category>;
  tags: StrapiCollection<Tag>;
  feedbacks: StrapiCollection<ArtFeedback>;
  likers: StrapiCollection<User>;
  collection: StrapiEntity<Collection>;
  comments: StrapiCollection<Comment>;
  localizations: StrapiCollection<Art>;
  createdAt: string;
  publishedAt: string;
  updatedAt: string;
};
